services:
  - type: web
    name: neura-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONPATH
        value: "."